[package]
name = "rcb"
version = "0.1.0"
authors = ["John Kåre Alsaker <john.kare.alsaker@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.5"
clap = "2.33.3"
serde = "1.0.123"
serde_derive = "1.0.123"
